name: androidtvapp
description: A new Flutter project.

publish_to: "none"

version: 1.2.0+2

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  webview_flutter:
  cached_network_image: ^3.3.0
  cherry_toast: ^1.6.4
  chewie: ^1.7.1
  cupertino_icons: ^1.0.2
  dio: ^5.3.3
  firebase_analytics: ^10.6.2
  firebase_core: ^2.20.0
  firebase_messaging: ^14.7.2
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  font_awesome_flutter: ^10.5.0
  google_fonts: ^6.1.0
  # google_mobile_ads: ^3.1.0
  intl: any
  provider: ^6.0.5
  video_player: ^2.7.2
  youtube_player_flutter: ^8.1.2

dev_dependencies:
  change_app_package_name: ^1.1.0
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/vectors/
    - assets/images/
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
